name: Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990  # v8.3.2
        with:
          enable-cache: true
          python-version: '3.12'
      - run: uv venv
      - run: uv pip install -r requirements.txt -r requirements-dev.txt
      - run: uv run pytest -q
